---
title       : Brief Introduction to Pricing Derivatives
subtitle    : Pricing a Call Option with a Two Step Binomial Model
author      : Robby Twesten & Tristan McDougall 
job         : RT Financials
framework   : io2012     # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, bootstrap]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Outline
### Tools:  
1. Programming Environment
2. Probability
3. Calculus

### Finance Theory:  
1. Future Value of Money
2. Binomial Tree Pricing Model for Option

### Conclusions

--- .class #id

## Programming Environment

### R is a free statistical software package with integrated graphics
* [Open Source Code](http://cran.r-project.org/), Shared Libraries, & [Integrated Development Environment](http://www.rstudio.com/) 
```{r echo=FALSE, warning=FALSE, results='hide', message=FALSE}
require(stringr)
require(slidify)
require(knitr)
require(DiagrammeR)
```

* [Plotting](http://ggplot2.org/), [LaTex](http://www.latex-project.org/) for equations, & [Slide Presentations](https://github.com/ramnathv/slidifyExamples)

### Version Control
* [Git](https://www.git-scm.com) invented by Linus Torvalds (open source Linux)
* [Git Hub](https://github.com/RobertTwesten/Tristan) distributed version control ([used by Google](https://github.com/google))

---
## Tools from Calculus

### Definition of $e$

<div class="centered">
\begin{equation}
    e = \lim_{n\to\infty} (1 + n)^{1/n}
\end{equation}
</div>

### Integration

* Assume a [linear measure]( http://en.wikipedia.org/wiki/Measure_(mathematics\) ) in $\Re^1$, then
\begin{equation}
    \int dx = x + C
\end{equation}

### Total Derivative

* Let $f$ be a function of $x(t)$, $y(t)$, and $t$. The total derivative with respect to time is

\begin{equation}
    \frac{d f(x(t), y(t), t)}{d t} = \frac{\partial f}{\partial x} \frac{d x}{d t} + \frac{\partial f}{\partial y} \frac{d y}{d t}
    + \frac{\partial f}{\partial t} \frac{d t}{d t}
\end{equation}

---
## Tools from Statistics

### Observations
* Given a set of observations $\{x_i\}$, the mean is

<div class="centered">
\begin{equation}
    \mu =  \sum_{i=1}^{n} \frac{x_i}{n}
\end{equation}
</div>


* The variance (a measure of disorder) is

<div class="centered">
\begin{equation}
   \sigma^2  =  \sum_{i=1}^n \frac{(x_i - \mu)^2}{n}
\end{equation}
</div>

\begin{equation}
\vdots
\end{equation}

<div class="centered">
\begin{equation}
   \sigma^2  =  E[x^2] - E[x]^2
\end{equation}
</div>

---
## Tools from Probability
### [Stochastic Processes](http://en.wikipedia.org/wiki/Stochastic_process): observations whose values are random with respect to time


### Markov Process
* Future stock price depends only on current price.
* Distributions are normal. Means are additive. Variances are additive.

### Wiener Process

* Future stock price depends only on current price.
* Distributions are standard normal, i.e. $\mu = 0$ &  $\sigma^2 = 1$.

---
## Tools from Stochastic Calculus

### Ito's Lemma
* Show definition of Ito's lemma

---
## Definitions from Finance

### Stock
* An asset that is partial ownership of a publicly traded firm.


### European Option
* Right to buy (long) or sell (short) an asset (stock) for a strike price at a set time (maturity), for a fee today.


### Call Option
*  The option to buy a stock in the future at a fixed price.
* Two sides:  a buyer and a seller

### Put Option
* The option to sell a stock in the fture at a fixed price.
* Two sides:  a buyer and a seller


---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$

---

## Future Value of Money


r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$
  
### Example:
$$ r = 10\% $$
$$ Pv = $100 $$
$$ Fv_1 = ? $$

---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$
  
### Example:
$$ Fv_1 = $100 + (10\%)($100) $$
$$ Fv_1 = $110 $$

---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$

---

## Future Value of Money


r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$


$$ Fv_2 = (Fv_1) + r(Fv_1) $$

---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$

$$ Fv_2 = (Fv_1) + r(Fv_1) $$

$$ Fv_2 = (Pv + r(Pv)) + r(Pv + r(Pv)) $$

---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$

$$ Fv_2 = (Fv_1) + r(Fv_1) $$


$$ Fv_2 = (Pv + r(Pv)) + r(Pv + r(Pv)) $$






$$ Fv_2 = Pv(1 + 2r + r^2) $$




$$ Fv_2 = Pv(1+r)^2 $$

---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money
$$ Fv_1 = Pv + r(Pv) $$



$$ Fv_2 = Pv(1+r)^2 $$

$$ Fv_t = Pv(1+r)^t $$




$$ Fv_t = Pv(1+\frac{r}{n})^{nt} $$


### -t is a time step
### -n is a unit conversion

---

## Future Value of Money

r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money  
n = Unit Conversion  
t = Time Conversion

$$ Fv_t = Pv(1+\frac{r}{n})^{nt} $$

$$ k = \frac{n}{r} $$

$$ n = k*r $$


$$ Fv_t = Pv(1+\frac{1}{k})^{krt} $$

---

## Future Value of Money
r = risk free interest rate   
Pv = Present Value of Money  
Fv = Future Value of Money  

$$  e = \lim_{x\to\infty} (1+\frac{1}{x})^x $$

$$ Fv_t = Pv(\lim_{k\to\infty} (1+\frac{1}{k})^{k})^{rt} $$

$$ Fv_t = Pv (e^{rt}) $$

---
## Future Value of Money

* Graphs showing discrete compounding versus continuous compounding

---
## Risk Neutral Valuation of a Portfolio

### Assumptions
1. The expected return on a stock (or any other investment) is the risk-free rate.
2. The discount rate used for the expected payoff on an option (or any other instrument) is the risk-free rate.

### Purpose
1. Risk Neutral Valuation (RNV) simplifies pricing.

All returns and discounts are at risk-free rate.

2. Relationship between stock and derivative is the same regardless of risk.

Risk incorporated into price of stock.

---

## Binomial Tree Model

---

## Portfolio Management

### Risk Free Portfolio (RFP)
* Value of portfolio is same whether stock price goes up or down:

\begin{equation}
    (\Delta S_o) u - f_u = (\Delta S_o) d - f_d
\end{equation}

### $\Delta$ Hedge
* Determine number of shares $\Delta$ required for creating a RFP

\begin{equation}
    \Delta = \frac{f_u - f_d}{S_o (u-d)}
\end{equation}

---
## Pricing Slides (to be done)

* Integration of Stock price $\Delta S / S$ etc.
* Two properties are:

1.  The change $\Delta z$ during a small period of time $\Delta t$ is $\Delta z = \epsilon \sqrt(\Delta t)$ where $\epsilon$ is a standard normal distribution $\Phi(0,1)$.
2.  The values of $\Delta z$ for any two different short intervals of time, $\Delta t$, are independent.

